extend type Article {
  """
  ✨ List `Revision` objects in a one-to-many relationship (where `Revision`.`article` is this object).
  """
  revisions_on_article(
    """
    Filter condition to narrow down the query results.
    """
    where: Revision_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Revision_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Revision_Having
  ): [Revision!]! @fdc_generated(from: "Revision.article", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Article", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Article` table.
  """
  _count: Int! @fdc_generated(from: "Article.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `authorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  authorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.authorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `categoryId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoryId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.categoryId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `embedding` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  embedding_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.embedding", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `isPublished` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPublished_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.isPublished", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `slug` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  slug_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.slug", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Article` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Article.title", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `content` field in the `Article` table.
  """
  content_min: Any @fdc_generated(from: "Article.content", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Article` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Article.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `content` field in the `Article` table.
  """
  content_max: Any @fdc_generated(from: "Article.content", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Article` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Article.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Article.id", purpose: ENTITY_ID)
}
extend type Category {
  """
  ✨ List `Article` objects in a one-to-many relationship (where `Article`.`category` is this object).
  """
  articles_on_category(
    """
    Filter condition to narrow down the query results.
    """
    where: Article_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Article_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Article_Having
  ): [Article!]! @fdc_generated(from: "Article.category", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Category` objects in a one-to-many relationship (where `Category`.`parent` is this object).
  """
  categories_on_parent(
    """
    Filter condition to narrow down the query results.
    """
    where: Category_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Category_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Category_Having
  ): [Category!]! @fdc_generated(from: "Category.parent", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Category", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Category` table.
  """
  _count: Int! @fdc_generated(from: "Category.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `parentId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parentId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.parentId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Category.id", purpose: ENTITY_ID)
}
extend type Revision {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Revision", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Revision` table.
  """
  _count: Int! @fdc_generated(from: "Revision.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Revision` table where the `articleId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  articleId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Revision.articleId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Revision` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Revision.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Revision` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Revision.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Revision` table where the `savedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  savedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Revision.savedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Revision` table where the `savedById` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  savedById_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Revision.savedById", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `content` field in the `Revision` table.
  """
  content_min: Any @fdc_generated(from: "Revision.content", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `savedAt` field in the `Revision` table.
  """
  savedAt_min: Timestamp @fdc_generated(from: "Revision.savedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `content` field in the `Revision` table.
  """
  content_max: Any @fdc_generated(from: "Revision.content", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `savedAt` field in the `Revision` table.
  """
  savedAt_max: Timestamp @fdc_generated(from: "Revision.savedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Revision.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Article` objects in a one-to-many relationship (where `Article`.`author` is this object).
  """
  articles_on_author(
    """
    Filter condition to narrow down the query results.
    """
    where: Article_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Article_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Article_Having
  ): [Article!]! @fdc_generated(from: "Article.author", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Revision` objects in a one-to-many relationship (where `Revision`.`savedBy` is this object).
  """
  revisions_on_savedBy(
    """
    Filter condition to narrow down the query results.
    """
    where: Revision_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Revision_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Revision_Having
  ): [Revision!]! @fdc_generated(from: "Revision.savedBy", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.role", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
